version: '3'

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s  docker-entrypoint.sh node index.js
    hostname: node
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - node-nginx-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    hostname: nginx
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - node-nginx-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always 
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-nginx-network

networks:
  node-nginx-network:
    external: true